FROM node:11-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY src ./
COPY .env ./
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY tslint.json ./
COPY nodemon.json ./

RUN apk add --no-cache bash python2
# CMD npm install ; npm install -g nodemon

EXPOSE 5000
